name: Upload to S3

on:
  push:
    branches:
      - master

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: AWS Deploy S3
      uses: oneyedev/aws-deploy-s3@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        bucket-name: arn:aws:s3:::bucketforrami1
        source: ./html
        destination: https://s3.console.aws.amazon.com/s3/buckets/bucketforrami1?region=us-east-1&prefix=html/
